"""add academic scheduling tables

Revision ID: c4eee4af0a62
Revises: abc6f7f8af73
Create Date: 2026-08-17 20:27:33.865565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4eee4af0a62'
down_revision: Union[str, Sequence[str], None] = 'abc6f7f8af73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_conversations_user_id'), 'assistant_conversations', ['user_id'], unique=False)
    op.create_table('calendar_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(length=50), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_accounts_user_id'), 'calendar_accounts', ['user_id'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conflict_type', sa.String(length=80), nullable=False),
    sa.Column('severity', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_entity_type', sa.String(length=80), nullable=True),
    sa.Column('affected_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_user_id'), 'conflicts', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('related_entity_type', sa.String(length=80), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_scheduled_for'), 'notifications', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('instructor', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('weekly_target_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_user_id'), 'subjects', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_study_start', sa.String(length=5), nullable=False),
    sa.Column('preferred_study_end', sa.String(length=5), nullable=False),
    sa.Column('max_session_minutes', sa.Integer(), nullable=False),
    sa.Column('min_session_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('allow_auto_reschedule', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('assistant_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_intent', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['assistant_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_messages_conversation_id'), 'assistant_messages', ['conversation_id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_account_id', sa.Integer(), nullable=True),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('rrule', sa.Text(), nullable=True),
    sa.Column('recurrence_exception', sa.Text(), nullable=True),
    sa.Column('parent_event_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_busy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_account_id'], ['calendar_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_calendar_account_id'), 'calendar_events', ['calendar_account_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_end_at'), 'calendar_events', ['end_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_external_event_id'), 'calendar_events', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_at'), 'calendar_events', ['start_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('exam_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('study_required_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_exam_at'), 'exams', ['exam_at'], unique=False)
    op.create_index(op.f('ix_exams_subject_id'), 'exams', ['subject_id'], unique=False)
    op.create_index(op.f('ix_exams_user_id'), 'exams', ['user_id'], unique=False)
    op.create_table('productivity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('missed_tasks', sa.Integer(), nullable=False),
    sa.Column('productive_hour', sa.Integer(), nullable=True),
    sa.Column('adherence_score', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productivity_records_record_date'), 'productivity_records', ['record_date'], unique=False)
    op.create_index(op.f('ix_productivity_records_subject_id'), 'productivity_records', ['subject_id'], unique=False)
    op.create_index(op.f('ix_productivity_records_user_id'), 'productivity_records', ['user_id'], unique=False)
    op.create_table('scheduling_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conflict_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=80), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('proposed_changes', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conflict_id'], ['conflicts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduling_recommendations_conflict_id'), 'scheduling_recommendations', ['conflict_id'], unique=False)
    op.create_index(op.f('ix_scheduling_recommendations_user_id'), 'scheduling_recommendations', ['user_id'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_account_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('events_created', sa.Integer(), nullable=False),
    sa.Column('events_updated', sa.Integer(), nullable=False),
    sa.Column('events_deleted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calendar_account_id'], ['calendar_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_calendar_account_id'), 'sync_logs', ['calendar_account_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_user_id'), 'sync_logs', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_minutes', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_deadline_at'), 'tasks', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_tasks_subject_id'), 'tasks', ['subject_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_end_at'), 'study_sessions', ['end_at'], unique=False)
    op.create_index(op.f('ix_study_sessions_start_at'), 'study_sessions', ['start_at'], unique=False)
    op.create_index(op.f('ix_study_sessions_subject_id'), 'study_sessions', ['subject_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_task_id'), 'study_sessions', ['task_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), server_default='', nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('study_goal_minutes_per_week', sa.Integer(), server_default='900', nullable=False))
    op.alter_column('users', 'password_hash', server_default=None)
    op.alter_column('users', 'is_active', server_default=None)
    op.alter_column('users', 'study_goal_minutes_per_week', server_default=None)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'study_goal_minutes_per_week')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'password_hash')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_task_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_subject_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_start_at'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_end_at'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_subject_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_sync_logs_user_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_calendar_account_id'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_scheduling_recommendations_user_id'), table_name='scheduling_recommendations')
    op.drop_index(op.f('ix_scheduling_recommendations_conflict_id'), table_name='scheduling_recommendations')
    op.drop_table('scheduling_recommendations')
    op.drop_index(op.f('ix_productivity_records_user_id'), table_name='productivity_records')
    op.drop_index(op.f('ix_productivity_records_subject_id'), table_name='productivity_records')
    op.drop_index(op.f('ix_productivity_records_record_date'), table_name='productivity_records')
    op.drop_table('productivity_records')
    op.drop_index(op.f('ix_exams_user_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_subject_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_exam_at'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_external_event_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_end_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_calendar_account_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_assistant_messages_conversation_id'), table_name='assistant_messages')
    op.drop_table('assistant_messages')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_subjects_user_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_scheduled_for'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_conflicts_user_id'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_calendar_accounts_user_id'), table_name='calendar_accounts')
    op.drop_table('calendar_accounts')
    op.drop_index(op.f('ix_assistant_conversations_user_id'), table_name='assistant_conversations')
    op.drop_table('assistant_conversations')
    # ### end Alembic commands ###
