"""add secondary_entity_id to conflicts

Revision ID: d66f07d816a5
Revises: c4eee4af0a62
Create Date: 2026-08-28 20:59:46.426898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66f07d816a5'
down_revision: Union[str, Sequence[str], None] = 'c4eee4af0a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conflicts', sa.Column('secondary_entity_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conflicts', 'secondary_entity_id')
    # ### end Alembic commands ###
